### ISSUE TITLE
Banner no se muestra bien

### ISSUE THREAD

**Issue by snahuel99** [GeraZorzoni/Zorzoni-ML#1]
Hola Gera como estas? Ahí vi que el banner no se ve del todo bien ni ocupa todo el ancho, tal vez probaría ponerlo fuera del header. Saludos!

**Comment by GeraZorzoni** [comment]
Nahu , gracias por mirarlo, tenias razon! no me habia dado cuenta que le faltaba un poquito en los margenes, tome tu consejo y quedo genial ahora, saludos!

**Comment by GeraZorzoni** [comment]
Listo
